load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "pinned_interpreter",
    srcs = [
        "main.cpp",
        "native_trap.cpp",
        "//luau:interpreter_header_files",
        "//luau:interpreter_sources",
        "//runtime:runtime_patch_headers",
    ],
    copts = ["-std=c++17"],
    data = [
        "//conformance/sources:embed_lib",
        "//conformance/sources:embed_main",
    ],
    deps = [
        "//runtime:runtime_patch_incs",
        "//luau:interpreter_headers",
    ],
    visibility = ["//visibility:public"],
)
