import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const WORKSPACE = dirname(dirname(fileURLToPath(import.meta.url)));

const ROOTS = [
  "compiler/compiler_host.zig",
  "compiler/compiler_entry.zig",
  "compiler/link",
  "compiler/backend/plan",
  "compiler/backend/emit",
  "compiler/backend/lower",
  "schema",
  "frontend/frontend_adapter.cpp",
];

function collect(dir, out) {
  for (const name of readdirSync(dir).sort()) {
    const path = join(dir, name);
    const st = statSync(path);
    if (st.isDirectory()) collect(path, out);
    else if (name.endsWith(".test.zig")) continue;
    else if (name.endsWith(".zig") || name.endsWith(".cpp") || name.endsWith(".c") || name.endsWith(".h")) {
      out.push(path);
    }
  }
}

export function compilerSourceFiles(workspace = WORKSPACE) {
  const files = [];
  for (const root of ROOTS) {
    const path = join(workspace, root);
    const st = statSync(path);
    if (st.isDirectory()) collect(path, files);
    else files.push(path);
  }
  return files.sort();
}

export function hashCompilerSources(workspace = WORKSPACE) {
  const hash = createHash("sha256");
  for (const path of compilerSourceFiles(workspace)) {
    hash.update(path.slice(workspace.length + 1));
    hash.update("\0");
    hash.update(readFileSync(path));
  }
  return hash.digest();
}

export function generateCompilerBuildDigest(workspace = WORKSPACE) {
  const digest = hashCompilerSources(workspace);
  const hex = digest.toString("hex");
  const bytes = [...digest].map((value) => `0x${value.toString(16).padStart(2, "0")}`);
  const rows = [];
  for (let index = 0; index < bytes.length; index += 8) {
    rows.push(`    ${bytes.slice(index, index + 8).join(", ")},`);
  }
  return {
    hex,
    zig: `// Generated by tools/generate_compiler_build_digest.mjs from compiler code sources.
pub const compiler_build_sha256 = [_]u8{\n${rows.join("\n")}\n};\n`,
    json: `${JSON.stringify({ sha256: hex }, null, 2)}\n`,
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const generated = generateCompilerBuildDigest();
  writeFileSync(join(WORKSPACE, "compiler/compiler_build_digest.zig"), generated.zig);
  writeFileSync(join(WORKSPACE, "compiler/compiler_build_digest.json"), generated.json);
  process.stdout.write(`${generated.hex}\n`);
}
